demo:
  users:
    - username: admin
      password: admin123
      role: ADMIN
    - username: manager1
      password: manager123
      role: MANAGER
    - username: support1
      password: support123
      role: SUPPORT
    - username: user1
      password: user123
      role: USER

server:
  port: 0

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/auth-db

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:verySecureRandomKeyForDevelopmentOnlyThisKeyMustBeAtLeast64BytesLongForHS512AlgorithmToWorkProperly}
  expiration: 43200000  # 12 hours in milliseconds
