server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/v1/inventory/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:verySecureRandomKeyForDevelopmentOnly}
