server:
  port: 0

spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/inventory-db

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
